#!/bin/bash

PROVIDERS=$(xrandr --listproviders)

if [[ $PROVIDERS == *"NVIDIA"* ]]; then
	CARD="<span foreground='#77b900'>nvidia</span>"
 else
	CARD="<span foreground='#D3DAE3'>i915</span>"
fi

case $BLOCK_BUTTON in
    3) pkill xorg && nvidia-xrun i3;;
esac

echo "gpu:$CARD"
